import mongoose from 'mongoose';

const quoteSchema = new mongoose.Schema(
  {
    customerId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Customer',
      required: true,
      index: true,
    },
    conversationId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Conversation',
      default: null,
    },
    pickup: { type: String, required: true, trim: true },
    dropoff: { type: String, required: true, trim: true },
    date: { type: Date, required: true },
    vehicleType: { type: String, required: true, trim: true },
    passengers: { type: Number, required: true, min: 1 },
    notes: { type: String, default: '' },
    status: {
      type: String,
      enum: ['new', 'quoted', 'won', 'lost'],
      default: 'new',
      index: true,
    },
    quotedPrice: { type: Number, default: null },
    customerName: { type: String, required: true },
    customerContact: { type: String, required: true },
    // Expanded lead fields (info.md integration)
    language: { type: String, enum: ['ar', 'en', ''], default: '' },
    customerType: {
      type: String,
      enum: [
        '',
        'individual',
        'company',
        'government',
        'school',
        'hajj_mission',
      'umrah_campaigns',
        'tourism',
        'group',
        'corporate',
      ],
      default: '',
      index: true,
    },
    organization: { type: String, default: '', trim: true },
    email: { type: String, default: '', trim: true },
    serviceType: { type: String, default: '', trim: true, index: true },
    originCity: { type: String, default: '', trim: true },
    destinationCity: { type: String, default: '', trim: true },
    returnDatetime: { type: Date, default: null },
    tripType: { type: String, default: '', trim: true },
    busCount: { type: Number, default: null, min: 1 },
    busClass: { type: String, default: '', trim: true },
    luggageNotes: { type: String, default: '' },
    accessibilityNeeds: { type: String, default: '' },
    specialRequirements: { type: String, default: '' },
    stops: { type: String, default: '', trim: true },
    departureTime: { type: String, default: '', trim: true },
    waitingHours: { type: Number, default: null, min: 0 },
    needsSupervisors: { type: Boolean, default: false },
    needsTracking: { type: Boolean, default: false },
    needsBranding: { type: Boolean, default: false },
    needsAirportReception: { type: Boolean, default: false },
    leadId: { type: String, default: '', trim: true, index: true },
    preferredContactChannel: {
      type: String,
      enum: ['', 'phone', 'whatsapp', 'email', 'web'],
      default: '',
    },
    consent: { type: Boolean, default: false },
    priority: {
      type: String,
      enum: ['normal', 'high', 'urgent'],
      default: 'normal',
    },
    assignedDepartment: {
      type: String,
      enum: ['', 'sales', 'hajj', 'corporate', 'operations', 'support'],
      default: '',
      index: true,
    },
  },
  { timestamps: true }
);

export const Quote = mongoose.models.Quote || mongoose.model('Quote', quoteSchema);
